### ISSUE TITLE
🐛 FIX: Name

### ISSUE THREAD

**Issue by ahmadawais** [ahmadawais/Shades-of-Purple-Konsole#1]
Thanks for creating a theme for Konsole @rahilwazir 🙌

Creating a few issues to address things I think should be fixed.

The name should be: `Shades of Purple`

https://github.com/ahmadawais/Shades-of-Purple-Konsole/blob/c6d1f3e6f7f8810bccc2e9e659b57ab3fe74eea0/Shades%20Of%20Purple.colorscheme#L92

Can we also change the file name to `shades-of-purple.colorscheme`.

@rahilwazir also use the same git log commit messages as the title of issues.

Make sure you read this:

https://gist.github.com/ahmadawais/815ea20134cf4616a6b2a965eb08f716

**Comment by rahilwazir** [comment]
Fixed in https://github.com/ahmadawais/Shades-of-Purple-Konsole/commit/6c5c2c599a1dd3e3cb5bb081ab6d7d6109512946.
