### ISSUE TITLE
 📖 DOC: Add Contributors names and links

### ISSUE THREAD

**Issue by ahmadawais** [ahmadawais/Shades-of-Purple-Konsole#3]
Below "Licensed as MIT ⓒ Ahmad Awais." in the readme.md create a new line with this

**Contributors**: [Rahil Wazir](https://github.com/rahilwazir)

**Comment by rahilwazir** [comment]
Done, thanks. :ok_hand: https://github.com/ahmadawais/Shades-of-Purple-Konsole/commit/8c2208d240c6b8e6a721a111e1b204e2f8b21b51

**Comment by rahilwazir** [comment]
Removed alternative installation method in https://github.com/ahmadawais/Shades-of-Purple-Konsole/commit/83ac9c1b2ce06a3d2bd03c8ecd56273db11d23a4, it was for Hyper.js.
