### ISSUE TITLE
👌 IMPROVE: Color Adjustments

### ISSUE THREAD

**Issue by ahmadawais** [ahmadawais/Shades-of-Purple-Konsole#4]
Here're a few color adjustments. 

Change the colors in the screenshot on left with hex codes on right.

Screenshot of a Color | Hex Color You Should Use | 
--- | --- |
![image](http://on.ahmda.ws/qb7n/c) | `#5D3DE1` | 
![image](http://on.ahmda.ws/qbLl/c) | `#A599E9` or `#CEC5FF` | 

Here are the ANSI colors use any of these with the following E.g. green, red, blue, cyan, magenta, etc.

Color Name | Hex Color You Should Use | 
--- | --- |
| "ansiBlack" | `#000000` |
| "ansiRed" | `#D90429` |
| "ansiGreen" | `#3ad900` |
| "ansiYellow" | `#FAD000` |
| "ansiBlue" | `#6943ff` |
| "ansiMagenta" | `#ff2c70` |
| "ansiCyan" | `#80fcff` |
| "ansiWhite" | `#ffffff` |
| "ansiBrightBlack" | `#000000` |
| "ansiBrightRed" | `#D90429` |
| "ansiBrightGreen" | `#3ad900` |
| "ansiBrightYellow" | `#FAD000` |
| "ansiBrightBlue" | `#6943ff` |
| "ansiBrightMagenta" | `#fb94ff` |
| "ansiBrightCyan" | `#80fcff` |

Best of luck.
Peace! ✌️

**Comment by rahilwazir** [comment]
@ahmadawais 
Adjusted the first color `#5D3DE1`. As for the second one I'm unable to change it through Konsole color scheme, maybe the color is being applied by `powerlevel9k` zsh theme?

![download](https://user-images.githubusercontent.com/1818941/38175290-c96cce42-35f3-11e8-85bc-8a4f60226a97.png)

**Comment by ahmadawais** [comment]
OK, if you can't do that then looks good to me already 👍
